### ISSUE TITLE
Use GitHub environments for deployment approvals

### ISSUE THREAD

**Issue by willgriffin** [willgriffin/startup-gitops-template#10]
## Description
The workflow deploys directly to production without any approval gates or environment-specific configurations, missing GitHub environments protection capabilities.

## Problem
- No approval required for production deployments
- No environment-specific secrets
- Missing deployment history tracking
- No protection rules enforced

## Proposed Solution
1. Create GitHub environments (staging, production)
2. Add environment protection rules
3. Require approvals for production
4. Use environment-specific secrets
5. Track deployment history

## Implementation Example
```yaml
jobs:
  deploy-infrastructure:
    environment:
      name: production
      url: https://${{ needs.validate-config.outputs.primary-domain }}
    # Rest of job...

# In repository settings:
# - Create "production" environment
# - Add required reviewers
# - Add deployment branch restrictions
# - Configure environment secrets
```

## Configuration Steps
1. Settings → Environments → New environment
2. Add protection rules:
   - Required reviewers
   - Restrict deployment branches to main
   - Add environment secrets
3. Update workflow to use environment

## Benefits
- Deployment approval workflow
- Environment-specific configurations
- Deployment history and rollback
- Better access control
- Audit compliance

## References
- No environment configuration in workflow
- All deployments are immediate
- Could integrate with deploy-infrastructure job
