### ISSUE TITLE
feat: Add interactive form and workflow for initial setup

### ISSUE THREAD

**Issue by willgriffin** [willgriffin/startup-gitops-template#16]
### Overview
Add a GitHub Actions workflow with `workflow_dispatch` that provides an interactive form for users when they create a new repository from this template. This would streamline the initial configuration process and reduce manual editing of configuration files.

#### How It Works
1. **Interactive Workflow**: Use `workflow_dispatch` with input parameters to create a form-based setup
2. **User Experience**: Users go to Actions tab → "Initial Setup" workflow → "Run workflow" button → fill form → click "Run"
3. **Automated Configuration**: The workflow processes form inputs to customize the repository

#### Form Inputs
```yaml
workflow_dispatch:
  inputs:
    domain_name:
      description: 'Your domain name (e.g., example.com)'
      required: true
      type: string
    digitalocean_token:
      description: 'DigitalOcean API Token'
      required: true
      type: string
    cluster_name:
      description: 'Kubernetes cluster name'
      required: true
      default: 'cumulus'
      type: string
    email:
      description: 'Email for Let\'s Encrypt certificates'
      required: true
      type: string
    enable_keycloak:
      description: 'Enable Keycloak identity provider'
      required: false
      default: true
      type: boolean
    enable_mattermost:
      description: 'Enable Mattermost chat platform'
      required: false
      default: false
      type: boolean
    enable_nextcloud:
      description: 'Enable Nextcloud file storage'
      required: false
      default: false
      type: boolean
    enable_mailu:
      description: 'Enable Mailu email server'
      required: false
      default: false
      type: boolean
```

#### Workflow Steps
The workflow would:
1. Validate inputs (domain format, token validity)
2. Update `config.yaml` with provided values
3. Generate proper Terraform variable files
4. Update domain references throughout the codebase
5. Configure application-specific settings based on selections
6. Initialize encrypted secrets structure
7. Run existing setup scripts with new configuration
8. Commit all configured files
9. Provide summary of next steps

#### Benefits
- **Immediate execution** - no multi-step process or waiting
- **Built-in validation** - GitHub validates input types automatically
- **Clean UX** - single form interface, no leftover issues
- **Atomic operation** - everything happens in one workflow run
- **Error handling** - can provide clear feedback if setup fails

#### Why Interactive Workflow vs Issue-based
- **Simpler UX**: One-click "Run workflow" → fill form → done
- **No cleanup required**: No temporary issues to manage
- **Better validation**: GitHub's built-in input validation
- **Immediate feedback**: Workflow runs immediately after form submission
- **More reliable**: No timing issues or parsing complexities

### Implementation Considerations
- Should integrate with existing `scripts/initial-setup` script
- Needs to handle secrets generation and encryption properly
- Should validate DigitalOcean API token and domain ownership
- Must preserve the template's educational value while simplifying setup
- Consider masking sensitive inputs in workflow logs

### Files to Create/Modify
- `.github/workflows/initial-setup.yml` - Main interactive setup workflow
- Update existing setup scripts to accept parameters from workflow
- Add validation scripts for user input
- Update README with instructions for using the interactive setup

This feature would significantly improve the user experience by providing a guided, form-based setup process that's both immediate and foolproof.
