### ISSUE TITLE
CRITICAL: Missing Pod Security Contexts for All Applications

### ISSUE THREAD

**Issue by willgriffin** [willgriffin/startup-gitops-template#18]
## Summary
A comprehensive security audit revealed that **no applications in this template have Pod Security Contexts defined**, which is a critical security vulnerability.

## Impact
- Applications likely running as root (uid 0)
- Root filesystem is writable, allowing runtime modifications
- Privilege escalation is possible
- Containers can access host resources

## Evidence
Search for `securityContext` configurations returned no results across all YAML files.

## Affected Components
- Nextcloud deployment
- Mattermost deployment  
- Keycloak (via operator)
- All init containers

## Required Actions
1. Add `securityContext` to all Pod specs:
```yaml
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
```

2. Add `seccompProfile` for enhanced security:
```yaml
securityContext:
  seccompProfile:
    type: RuntimeDefault
```

## References
- [Kubernetes Security Best Practices](https://kubernetes.io/docs/concepts/security/)
- [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/)

## Priority
🔴 **CRITICAL** - Immediate fix required before production deployment.
