### ISSUE TITLE
SECURITY: No Network Policies for Traffic Segmentation

### ISSUE THREAD

**Issue by willgriffin** [willgriffin/startup-gitops-template#20]
## Summary
The template lacks Kubernetes Network Policies, allowing unrestricted pod-to-pod communication and potential lateral movement in case of compromise.

## Impact
- Any compromised pod can access any other pod/service
- No traffic segmentation between applications
- Violates defense-in-depth security principles
- Potential data exfiltration risks

## Current State
- No NetworkPolicy resources found in the repository
- All pods can communicate with all services by default
- Database access is unrestricted from any pod

### 1. Default Deny All
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```

### 2. Database Access Restrictions
- PostgreSQL databases should only be accessible by their respective applications
- Redis should only be accessible by applications that need caching

### 3. Ingress Controller Policies
- Only Traefik should receive external traffic
- Applications should only accept traffic from Traefik

### 4. DNS and System Access
- Allow DNS resolution (port 53)
- Allow necessary system communication

## Priority
🟡 **HIGH** - Should be implemented before production deployment.

## References
- [Kubernetes Network Policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/)
- [Network Policy Recipes](https://github.com/ahmetb/kubernetes-network-policy-recipes)
