### ISSUE TITLE
SECURITY: Missing Resource Limits and Requests

### ISSUE THREAD

**Issue by willgriffin** [willgriffin/startup-gitops-template#23]
## Summary
Several applications lack proper resource limits and requests, which can lead to resource exhaustion and denial of service attacks.

## Impact
- Applications can consume unlimited CPU/memory
- Potential cluster-wide resource starvation
- No protection against resource-based DoS attacks
- Poor scheduling decisions by Kubernetes

### 1. Traefik (Mostly OK)
✅ Has resource configuration in `flux/clusters/cumulus/core/traefik/release.yaml:54-60`

### 2. Nextcloud (Partial)
✅ Has resources in `deployment.yaml:101-107`

### 3. Mattermost (Partial) 
✅ Has resources in `deployment.yaml:83-89`

### 4. Init Containers (Missing)
❌ All `wait-for-db` init containers lack resource limits:
```yaml
initContainers:
- name: wait-for-db
  image: busybox:1.36
  # Missing resources section
```

### 5. Database Operators (Unknown)
❌ Need to verify CloudNativePG and Redis operator resource configurations

### 1. Add Resource Limits to Init Containers
```yaml
initContainers:
- name: wait-for-db
  image: busybox:1.36
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
```

### 2. Review Operator Configurations
- Check CloudNativePG operator resource limits
- Check Redis operator resource limits
- Check Keycloak operator resource limits

### 3. Add ResourceQuotas per Namespace
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: nextcloud
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
```

## Priority
🟡 **MEDIUM** - Important for cluster stability and security.

## References
- [Resource Management for Pods and Containers](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)
- [Resource Quotas](https://kubernetes.io/docs/concepts/policy/resource-quotas/)
