### ISSUE TITLE
SECURITY: Traefik Missing Security Headers and Rate Limiting

### ISSUE THREAD

**Issue by willgriffin** [willgriffin/startup-gitops-template#24]
## Summary
The Traefik configuration lacks essential security headers and rate limiting, exposing applications to various web-based attacks.

## Location
`flux/clusters/cumulus/core/traefik/release.yaml`

### 1. Security Headers
No middleware configured for security headers:
- `X-Frame-Options`
- `X-Content-Type-Options`
- `X-XSS-Protection`
- `Strict-Transport-Security`
- `Content-Security-Policy`
- `Referrer-Policy`

### 2. Rate Limiting
No rate limiting configured to prevent:
- DDoS attacks
- Brute force attacks
- API abuse

### 3. IP Allowlisting/Blocklisting
No IP filtering configured for administrative endpoints.

### 1. Security Headers Middleware
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: traefik
spec:
  headers:
    frameDeny: true
    contentTypeNosniff: true
    browserXssFilter: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
    customRequestHeaders:
      X-Forwarded-Proto: "https"
```

### 2. Rate Limiting Middleware
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rate-limit
  namespace: traefik
spec:
  rateLimit:
    burst: 50
    average: 30
```

### 3. Application Integration
Update ingress resources to use middleware:
```yaml
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-security-headers@kubernetescrd,traefik-rate-limit@kubernetescrd
```

## Impact of Current State
- Vulnerable to clickjacking attacks
- No HSTS protection
- Missing XSS protection headers
- Vulnerable to DDoS/brute force attacks
- No protection against MIME type confusion

## Priority
🟡 **HIGH** - Essential web security measures missing.

## References
- [Traefik Middleware Documentation](https://doc.traefik.io/traefik/middlewares/)
- [OWASP Secure Headers Project](https://owasp.org/www-project-secure-headers/)
