### ISSUE TITLE
CONFIGURATION: Hard-coded Domain Names Throughout Template

### ISSUE THREAD

**Issue by willgriffin** [willgriffin/startup-gitops-template#25]
## Summary
Multiple configuration files contain hard-coded domain names (\"happyvertical.com\" and related subdomains), reducing template reusability and requiring manual edits for each deployment.

## Impact
- Users must manually find and replace domain names in multiple files
- Error-prone deployment process
- Reduced template reusability
- Potential for missed domain references

### 1. Traefik Configuration
`flux/clusters/cumulus/core/traefik/release.yaml:25`
```yaml
service.beta.kubernetes.io/do-loadbalancer-hostname: "happyvertical.com"
```

`flux/clusters/cumulus/core/traefik/release.yaml:48`
```yaml
--certificatesresolvers.letsencrypt.acme.email=admin@happyvertical.com
```

### 2. Application Deployments
`flux/clusters/cumulus/applications/nextcloud/deployment.yaml:51`
```yaml
- name: NEXTCLOUD_TRUSTED_DOMAINS
  value: cloud.happyvertical.com
```

`flux/clusters/cumulus/applications/nextcloud/deployment.yaml:55`
```yaml
- name: OVERWRITEHOST
  value: cloud.happyvertical.com
```

### 3. Ingress Configurations
`flux/clusters/cumulus/services/keycloak/ingress.yaml:14,17`
```yaml
- auth.happyvertical.com
```

### 4. Mattermost Configuration
`flux/clusters/cumulus/applications/mattermost/deployment.yaml:44`
```yaml
- name: MM_SERVICESETTINGS_SITEURL
  value: https://chat.happyvertical.com
```

### 5. CORS Configuration
`flux/clusters/cumulus/applications/nextcloud/deployment.yaml:67`
```yaml
allowed_origins = ["https://cloud.happyvertical.com"]
```

### 1. ConfigMap-based Configuration
Create a central ConfigMap with domain information:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: domain-config
  namespace: flux-system
data:
  primary_domain: "example.com"
  auth_domain: "auth.example.com"
  chat_domain: "chat.example.com"
  cloud_domain: "cloud.example.com"
  mail_domain: "mail.example.com"
```

### 2. Environment Variable References
Update deployments to reference the ConfigMap:
```yaml
env:
- name: NEXTCLOUD_TRUSTED_DOMAINS
  valueFrom:
    configMapKeyRef:
      name: domain-config
      key: cloud_domain
```

### 3. Kustomize Replacements
Use Kustomize replacements for static configurations:
```yaml
replacements:
- source:
    kind: ConfigMap
    name: domain-config
    fieldPath: data.primary_domain
  targets:
  - select:
      kind: Ingress
    fieldPaths:
    - spec.tls[*].hosts[*]
```

## Priority
🟡 **MEDIUM** - Affects template usability and maintainability.

## References
- [Kustomize Replacements](https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_replacements_)
- [ConfigMap Documentation](https://kubernetes.io/docs/concepts/configuration/configmap/)
