### ISSUE TITLE
INFRASTRUCTURE: Single Points of Failure in Application Deployments

### ISSUE THREAD

**Issue by willgriffin** [willgriffin/startup-gitops-template#26]
## Summary
Most applications are configured with single replicas, creating multiple single points of failure that can impact service availability.

## Impact
- Service downtime during pod restarts/updates
- No fault tolerance for node failures
- Poor availability during maintenance
- Reduced resilience against failures

### Single Replica Deployments
1. **Nextcloud**: `replicas: 1` (line 9)
2. **Mattermost**: `replicas: 1` (line 9)  
3. **Keycloak**: `instances: 1` (line 7)
4. **Traefik**: `replicas: 1` (line 18) - Note: Required for ACME storage

### Shared Storage Dependencies
All applications use ReadWriteOnce (RWO) persistent volumes, which can only be mounted by one pod at a time, limiting horizontal scaling.

### 1. Database Session Affinity
- Nextcloud and Mattermost may have session affinity requirements
- File locking mechanisms need consideration

### 2. ACME Certificate Storage
- Traefik requires shared storage for Let's Encrypt certificates
- Multiple replicas need access to same ACME storage

### 3. Persistent Volume Types
- Current RWO volumes don't support multi-pod access
- Need ReadWriteMany (RWX) or alternative architectures

### 1. Traefik High Availability
```yaml
# Use ReadWriteMany storage or external certificate management
persistence:
  enabled: true
  storageClass: "rwx-storage-class"  # Or use cert-manager
```

### 2. Application Scaling Strategy
```yaml
# For stateless components
replicas: 2
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1
```

### 3. Pod Anti-Affinity
```yaml
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - nextcloud
        topologyKey: kubernetes.io/hostname
```

### 4. Session Management
- Configure external session storage (Redis)
- Use sticky sessions with load balancer
- Implement session replication

### 1. Application-Specific Requirements
- Test Nextcloud with multiple replicas
- Verify Mattermost clustering capabilities
- Assess Keycloak clustering needs

### 2. Storage Solutions
- Evaluate ReadWriteMany storage options (NFS, CephFS)
- Consider object storage for shared data
- Implement proper backup strategies

## Priority
🟡 **MEDIUM** - Important for production availability, but requires careful testing.

## References
- [Deployment Strategies](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy)
- [Pod Anti-Affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity)
