### ISSUE TITLE
SECURITY: Missing RBAC and Service Account Configuration

### ISSUE THREAD

**Issue by willgriffin** [willgriffin/startup-gitops-template#27]
## Summary
Applications are running with default service accounts and lack proper Role-Based Access Control (RBAC) configuration, violating the principle of least privilege.

## Impact
- Applications have unnecessary cluster permissions
- Potential privilege escalation vulnerabilities
- Non-compliance with security best practices
- Broad access to Kubernetes API

### 1. No Custom Service Accounts
All application deployments use the default service account:
- Nextcloud deployment
- Mattermost deployment
- Init containers

### 2. No RBAC Resources Found
No Role, ClusterRole, RoleBinding, or ClusterRoleBinding resources found for applications.

### 3. Default Permissions
Default service accounts may have access to:
- Secrets in the same namespace
- Basic API discovery
- Potentially broader access depending on cluster configuration

### 1. Create Service Accounts per Application
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextcloud
  namespace: nextcloud
automountServiceAccountToken: false  # Disable if API access not needed
```

### 2. Define Minimal Roles
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: nextcloud
  name: nextcloud
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["nextcloud-admin", "nextcloud-pg-app"]
  verbs: ["get"]
```

### 3. Bind Roles to Service Accounts
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextcloud
  namespace: nextcloud
subjects:
- kind: ServiceAccount
  name: nextcloud
  namespace: nextcloud
roleRef:
  kind: Role
  name: nextcloud
  apiGroup: rbac.authorization.k8s.io
```

### 4. Update Deployments
```yaml
spec:
  template:
    spec:
      serviceAccountName: nextcloud
      automountServiceAccountToken: false  # If no API access needed
```

## Security Benefits
- Principle of least privilege
- Limited blast radius if compromised
- Audit trail for API access
- Compliance with security standards

### 1. Nextcloud
- May need access to specific secrets
- Potentially no API access required

### 2. Mattermost  
- May need access to specific secrets
- Potentially no API access required

### 3. Operators
- Keycloak operator (should already have RBAC)
- CloudNativePG operator (should already have RBAC)
- Redis operator (should already have RBAC)

## Investigation Required
1. Audit current operator RBAC configurations
2. Determine if applications need Kubernetes API access
3. Review cluster-wide default permissions

## Priority
🟡 **HIGH** - Essential for proper security posture.

## References
- [RBAC Authorization](https://kubernetes.io/docs/reference/access-authn-authz/rbac/)
- [Service Accounts](https://kubernetes.io/docs/concepts/security/service-accounts/)
- [Security Best Practices](https://kubernetes.io/docs/concepts/security/)
