### ISSUE TITLE
Separate DigitalOcean Spaces credentials from API token

### ISSUE THREAD

**Issue by willgriffin** [willgriffin/startup-gitops-template#3]
## Description
The workflow currently uses the same DigitalOcean API token for both API operations and Spaces access (lines 190-192, 196-198), which violates the principle of least privilege.

## Problem
- Single credential has excessive permissions
- API token can access all DO resources, not just Spaces
- Security risk if token is compromised
- Violates security best practices

## Proposed Solution
1. Create separate Spaces access keys in DigitalOcean
2. Add new secrets: SPACES_ACCESS_KEY and SPACES_SECRET_KEY
3. Update workflow to use dedicated Spaces credentials
4. Update documentation for required secrets

## Implementation
```yaml
env:
  TF_VAR_do_token: ${{ secrets.DIGITALOCEAN_TOKEN }}
  TF_VAR_spaces_access_key: ${{ secrets.SPACES_ACCESS_KEY }}
  TF_VAR_spaces_secret_key: ${{ secrets.SPACES_SECRET_KEY }}
```

## Benefits
- Improved security posture
- Principle of least privilege
- Easier credential rotation
- Better audit trail

## References
- Lines 190-192, 196-198 in cluster-deploy.yml
- terraform/digitalocean/variables.tf lines 74-84
