### ISSUE TITLE
Cache tool installations in workflow

### ISSUE THREAD

**Issue by willgriffin** [willgriffin/startup-gitops-template#4]
## Description
The cluster-deploy workflow installs the same tools (age, SOPS, yq, kubectl) multiple times across different jobs, leading to inefficiency and slower deployments.

## Problem
- Duplicate tool installations in multiple jobs
- No caching between workflow runs
- Increased deployment time
- Unnecessary network usage

## Proposed Solution
1. Use GitHub Actions cache for tool binaries
2. Create a setup-tools composite action
3. Implement version-based cache keys
4. Cache tool installations by OS and version

## Implementation Example
```yaml
- name: Cache tools
  uses: actions/cache@v3
  with:
    path:  < /dev/null | 
      /usr/local/bin/age
      /usr/local/bin/sops
      /usr/bin/yq
    key: ${{ runner.os }}-tools-${{ hashFiles("**/tool-versions.txt") }}
```

## Benefits
- Faster workflow execution
- Reduced network bandwidth
- More reliable deployments
- Easier tool management

## References
- Tool installations in setup-secrets job (lines 63-72)
- Tool installations in generate-encrypted-secrets job (lines 239-248)
- yq installation in multiple places
