### ISSUE TITLE
Replace Traefik with Kong Gateway for Enhanced API Management and AI Monitoring

### ISSUE THREAD

**Issue by willgriffin** [willgriffin/startup-gitops-template#44]
## Overview

Replace the current Traefik ingress controller with Kong Gateway to gain advanced API gateway capabilities, better Knative integration, and AI token usage monitoring through Kong's AI Gateway plugin.

### Traefik Setup
- **Role**: Primary ingress controller handling all external traffic
- **TLS**: Integrated with cert-manager for automatic certificate management
- **DNS**: Works with external-dns for automatic record creation
- **Auth**: Routes to OAuth2-proxy for Keycloak authentication
- **Services**: Routes to Keycloak, Mattermost, Nextcloud, Mailu, Postal, Grafana, Prometheus, Sentry

### Limitations
- Basic ingress capabilities without advanced API gateway features
- No built-in API rate limiting or transformation
- Limited observability for API usage patterns
- No native support for AI/LLM token tracking
- Suboptimal integration with Knative

### Core Components
1. **Kong Gateway**
   - Hybrid deployment mode (control plane + data plane separation)
   - PostgreSQL backend (using CloudNativePG operator)
   - Redis caching layer (using Redis operator)
   - High availability with multiple replicas

2. **Kong Ingress Controller**
   - Kubernetes-native ingress management
   - Gateway API support (future-proof)
   - Automatic service discovery

3. **Kong Manager** (optional)
   - Web UI for configuration management
   - Secured with Keycloak OIDC

4. **Kong AI Gateway Plugin**
   - Token usage tracking per user/tenant
   - Multi-provider support (OpenAI, Anthropic, Cohere, etc.)
   - Cost allocation and budgeting
   - Rate limiting based on token consumption

#### Authentication & Authorization
- **Kong OIDC Plugin**: Direct integration with Keycloak
- **Key-Auth Plugin**: API key management
- **JWT Plugin**: Token validation
- Replace OAuth2-proxy with native Kong plugins

#### Knative Integration
- Kong as Knative network layer
- Serverless function routing
- Automatic scaling integration
- Request/response transformations

#### Observability
- **Prometheus Plugin**: Metrics export
- **OpenTelemetry Plugin**: Distributed tracing
- **File-Log Plugin**: Structured logging to Loki
- **AI Gateway Metrics**: Token usage, costs, latency per model

### Phase 1: Kong Infrastructure
1. Add Kong operator to controllers directory
2. Configure Kong gateway deployment manifests
3. Set up PostgreSQL and Redis dependencies
4. Add monitoring and logging configuration

### Phase 2: Service Configuration
1. **Replace Traefik manifests**:
   - Remove Traefik IngressRoute resources
   - Add Kong Ingress and HTTPRoute configurations

2. **Authentication services**:
   - Configure Kong OIDC plugin for Keycloak
   - Remove OAuth2-proxy deployments
   - Update service routing

3. **Application services**:
   - Convert all service ingress to Kong format
   - Add rate limiting and security policies
   - Configure request/response transformations

4. **Knative services**:
   - Configure Kong as Knative ingress
   - Add serverless routing policies
   - Enable auto-scaling integration

### Phase 3: AI Gateway Implementation
1. Deploy AI Gateway plugin
2. Configure LLM provider routes
3. Set up user token budgets and policies
4. Enable usage tracking and cost monitoring

### Phase 4: Template Integration
1. Update config.yaml.example with Kong options
2. Add Kong configuration to GitHub Actions workflow
3. Update documentation and examples
4. Add Kong-specific secret generation

### Basic Service + Route
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: nextcloud-ingress
  namespace: nextcloud
route:
  methods:
  - GET
  - POST
  strip_path: false
  preserve_host: true
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: nextcloud
  namespace: nextcloud
  annotations:
    konghq.com/plugins: nextcloud-oidc,nextcloud-rate-limit
spec:
  parentRefs:
  - name: kong
    namespace: kong
  hostnames:
  - cloud.{{ (datasource "config").domain }}
  rules:
  - backendRefs:
    - name: nextcloud
      port: 80
```

### OIDC Plugin Configuration
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: keycloak-oidc
  namespace: default
config:
  issuer: https://auth.{{ (datasource "config").domain }}/realms/master
  client_id: kong
  client_secret_vault: env/keycloak-client-secret
  discovery: https://auth.{{ (datasource "config").domain }}/realms/master/.well-known/openid-configuration
  scope: openid profile email
  redirect_uri: /auth/callback
plugin: openid-connect
```

### AI Gateway Configuration
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ai-gateway
  namespace: ai-services
config:
  providers:
  - name: openai
    endpoint: https://api.openai.com/v1
    models:
    - gpt-4
    - gpt-3.5-turbo
  - name: anthropic
    endpoint: https://api.anthropic.com/v1
    models:
    - claude-3-opus
    - claude-3-sonnet
  token_limits:
    default_daily: 100000
    default_monthly: 3000000
  cost_tracking:
    enabled: true
    currency: USD
  metrics:
    prometheus:
      enabled: true
      path: /metrics
plugin: ai-proxy
```

### API Management
- Centralized API gateway for all services
- Advanced routing and load balancing
- Request/response transformations
- API versioning support
- Circuit breaker patterns

### Security
- Native OIDC/OAuth2 integration
- API key management
- Rate limiting and DDoS protection
- Request validation
- IP restrictions

### Observability
- Detailed API analytics
- Token usage tracking
- Cost monitoring for AI services
- Performance metrics per endpoint
- User behavior insights

### Developer Experience
- Self-service API portal
- Automatic API documentation
- Testing and debugging tools
- SDK generation
- Usage dashboards

### Config.yaml Updates
```yaml
# Gateway Configuration
gateway:
  provider: kong  # or traefik for backwards compatibility
  kong:
    ai_gateway:
      enabled: true
      providers:
        - openai
        - anthropic
    rate_limiting:
      enabled: true
      default_limits:
        requests_per_minute: 1000
    monitoring:
      enabled: true
      prometheus_metrics: true
```

### Kong Gateway
- **Control Plane**: 2 replicas, 1 CPU, 2Gi memory each
- **Data Plane**: 3 replicas, 2 CPU, 4Gi memory each
- **PostgreSQL**: 1 cluster, 2 CPU, 4Gi memory, 20Gi storage
- **Redis**: 1 cluster, 1 CPU, 2Gi memory, 5Gi storage

## Success Criteria

1. Template deploys Kong Gateway successfully
2. All services accessible through Kong
3. AI token usage tracking operational
4. Enhanced monitoring capabilities
5. Successful Knative integration
6. Simplified authentication flow
7. Complete Traefik replacement

## Template Integration

- Add Kong manifests to flux/clusters/cumulus/
- Update GitHub Actions workflow with Kong options
- Modify config.yaml.example with gateway selection
- Update documentation and README
- Add Kong-specific examples and tutorials

## Timeline

- **Week 1-2**: Kong manifests and operator integration
- **Week 3-4**: Service configuration conversion
- **Week 5**: AI Gateway plugin implementation
- **Week 6**: Template integration and testing
- **Week 7**: Documentation and examples
- **Week 8**: Final testing and optimization
