### ISSUE TITLE
Migrate to External Secrets Operator with DigitalOcean App Platform Vault

### ISSUE THREAD

**Issue by willgriffin** [willgriffin/startup-gitops-template#45]
## Overview

Replace the current SOPS/Age-based secret management with the External Secrets Operator (ESO) integrated with DigitalOcean's App Platform Vault for centralized, secure secret management with automated rotation and enhanced operational security.

### Current Secret Management
- **SOPS + Age**: Secrets encrypted in Git repository
- **GitHub Actions**: Processes encrypted secrets during deployment
- **Manual Rotation**: Requires code changes and commits for secret updates
- **Limited Auditing**: No centralized audit trail for secret access
- **Git History**: Encrypted secrets stored in version control

### Template Limitations
- Secret rotation requires Git commits and deployments
- No real-time secret revocation capabilities
- Limited granular access control
- Difficult to audit secret usage patterns
- Manual secret distribution across environments
- Version control bloat with encrypted secret files

### Core Components

1. **External Secrets Operator**
   - Kubernetes-native secret synchronization
   - Multiple provider support (DigitalOcean, HashiCorp Vault, AWS, etc.)
   - Automatic secret refresh and rotation
   - Namespace isolation and RBAC integration

2. **DigitalOcean App Platform Vault**
   - Managed secret storage service
   - Built-in encryption at rest and in transit
   - API-based secret management
   - Integration with DO identity and access management
   - Audit logging and compliance features

3. **SecretStore Resources**
   - Per-namespace secret store configurations
   - Environment-specific secret scoping
   - Service account authentication
   - Connection pooling and caching

#### Authentication & Authorization
- **DO API Tokens**: Service account tokens for ESO
- **RBAC Integration**: Kubernetes service accounts mapped to DO access
- **Namespace Isolation**: Separate secret stores per application namespace
- **Least Privilege**: Minimal required permissions per service

#### Secret Categories
- **Database Credentials**: PostgreSQL, Redis passwords
- **OAuth Secrets**: Keycloak, OAuth2-proxy client secrets
- **API Keys**: External service credentials (SES, monitoring)
- **TLS Certificates**: Private keys for internal services
- **Application Secrets**: Session keys, encryption keys

### Phase 1: Template Infrastructure
1. Add External Secrets Operator to controllers directory
2. Create DigitalOcean SecretStore templates
3. Add service account and RBAC configurations
4. Configure base SecretStore templates per namespace

### Phase 2: Secret Template Conversion
1. **Replace secrets-template.yaml files**:
   - Convert to ExternalSecret CRDs
   - Map to DigitalOcean Vault paths
   - Maintain namespace isolation

2. **Update GitHub Actions**:
   - Remove SOPS decryption steps
   - Add DigitalOcean Vault population
   - Update secret initialization workflow

3. **Application configurations**:
   - Convert all secret references to ExternalSecret format
   - Add refresh intervals and rotation policies
   - Configure failure handling and fallbacks

### Phase 3: Template Integration
1. Update config.yaml.example with secret management options
2. Add External Secrets configuration to setup workflow
3. Create documentation and examples
4. Add secret store initialization scripts

### Phase 4: Cleanup and Enhancement
1. Remove SOPS-related files and documentation
2. Add secret monitoring and alerting
3. Implement secret rotation policies
4. Create troubleshooting guides

### SecretStore Template per Namespace
```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: digitalocean-vault
  namespace: {{ .namespace }}
spec:
  provider:
    digitalocean:
      auth:
        secretRef:
          accessToken:
            name: do-credentials
            key: access-token
      projectId: "{{ (datasource "config").digitalocean.project_id }}"
      environment: "{{ (datasource "config").environment }}"
```

### ExternalSecret for Database Credentials
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .app }}-db-credentials
  namespace: {{ .namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: digitalocean-vault
    kind: SecretStore
  target:
    name: {{ .app }}-postgres-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
  - secretKey: username
    remoteRef:
      key: {{ .app }}/database
      property: username
  - secretKey: password
    remoteRef:
      key: {{ .app }}/database
      property: password
```

### ExternalSecret for OAuth Configuration
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
  namespace: {{ .namespace }}
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: digitalocean-vault
    kind: SecretStore
  target:
    name: oauth2-proxy
    creationPolicy: Owner
  data:
  - secretKey: client-id
    remoteRef:
      key: keycloak/clients/{{ .app }}
      property: client_id
  - secretKey: client-secret
    remoteRef:
      key: keycloak/clients/{{ .app }}
      property: client_secret
  - secretKey: cookie-secret
    remoteRef:
      key: oauth2-proxy/{{ .app }}
      property: cookie_secret
```

### ClusterSecretStore for Global Secrets
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: digitalocean-global-vault
spec:
  provider:
    digitalocean:
      auth:
        secretRef:
          accessToken:
            name: do-global-credentials
            key: access-token
            namespace: external-secrets-system
      projectId: "{{ (datasource "config").digitalocean.project_id }}"
      environment: "{{ (datasource "config").environment }}"
  conditions:
  - namespaces:
    - cert-manager
    - monitoring
    - external-secrets-system
```

### Security Improvements
- **Centralized Management**: Single source of truth for all secrets
- **Audit Trail**: Complete logging of secret access and modifications
- **Automatic Rotation**: Scheduled credential updates
- **Real-time Revocation**: Immediate secret invalidation
- **Encryption**: At-rest and in-transit encryption by default
- **Compliance**: Meets enterprise security requirements

### Operational Benefits
- **No Git Commits**: Secret updates without code changes
- **Environment Parity**: Consistent secret management across deployments
- **Disaster Recovery**: External backup and restoration
- **Monitoring Integration**: Secret usage metrics and alerting
- **Developer Experience**: Self-service secret access

### Template Benefits
- **Production Ready**: Enterprise-grade secret management out of the box
- **Scalable**: Supports multi-tenant deployments
- **Maintainable**: Reduces secret management complexity
- **Flexible**: Multiple provider support for different environments
- **Observable**: Built-in monitoring and alerting

### Config.yaml Updates
```yaml
# Secret Management Configuration
secrets:
  provider: external-secrets  # or sops for backwards compatibility
  external_secrets:
    digitalocean:
      project_id: "your-project-id"
      environment: "production"
    refresh_interval: "1h"
    rotation:
      enabled: true
      schedule: "0 2 * * 0"  # Weekly on Sunday at 2 AM
```

### GitHub Actions Updates
```yaml
- name: Initialize DigitalOcean Vault
  if: inputs.secret_provider == 'external-secrets'
  run:  < /dev/null | 
    # Populate initial secrets in DO Vault
    scripts/init-external-secrets
```

### External Secrets Operator
- **Controller**: 1 replica, 0.5 CPU, 512Mi memory
- **Webhook**: 1 replica, 0.2 CPU, 256Mi memory
- **Cert Manager Integration**: Automatic certificate management

### DigitalOcean Vault
- **API Usage**: Pay-per-operation pricing model
- **Storage**: Encrypted secret storage
- **Bandwidth**: API calls for secret retrieval

## Success Criteria

1. Template deploys with External Secrets successfully
2. All secrets managed through DigitalOcean Vault
3. Automatic secret rotation operational
4. Comprehensive audit logging enabled
5. Reduced secret management complexity
6. Improved security posture
7. Enhanced operational visibility

## Template Integration

- Add External Secrets Operator to controllers
- Convert all secrets-template.yaml to ExternalSecret CRDs
- Update GitHub Actions workflow with vault initialization
- Modify config.yaml.example with secret management options
- Update documentation and examples
- Add troubleshooting guides

## Timeline

- **Week 1**: External Secrets Operator integration
- **Week 2**: Secret template conversion
- **Week 3**: GitHub Actions workflow updates
- **Week 4**: Template integration and testing
- **Week 5**: Documentation and examples
- **Week 6**: Final testing and optimization

## Dependencies

- DigitalOcean App Platform Vault access
- External Secrets Operator deployment
- Service account creation and RBAC configuration
- Monitoring stack integration (existing)

## References

- [External Secrets Operator Documentation](https://external-secrets.io/)
- [DigitalOcean App Platform Vault](https://docs.digitalocean.com/products/app-platform/concepts/security/)
- [Kubernetes Secret Management Best Practices](https://kubernetes.io/docs/concepts/configuration/secret/)
