### ISSUE TITLE
Add deployment notifications

### ISSUE THREAD

**Issue by willgriffin** [willgriffin/startup-gitops-template#5]
## Description
The cluster-deploy workflow provides no notifications on deployment success or failure, making it difficult to track deployment status without manually checking GitHub Actions.

## Problem
- No visibility into deployment status
- Manual checking required
- No alerts on failures
- Team members unaware of deployment outcomes

## Proposed Solution
1. Add notifications via GitHub issues on failure
2. Integrate with Slack/Discord webhooks
3. Create deployment status comments on PRs
4. Send email notifications for critical failures

## Implementation Ideas
```yaml
- name: Notify on failure
  if: failure()
  uses: actions/github-script@v6
  with:
    script:  < /dev/null | 
      github.rest.issues.create({
        owner: context.repo.owner,
        repo: context.repo.repo,
        title: "Deployment Failed: ${{ github.run_id }}",
        body: "Deployment failed. Check the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
      })
```

## Benefits
- Immediate awareness of issues
- Better team coordination
- Faster incident response
- Audit trail of deployments

## References
- No notification mechanism in current workflow
- Could integrate with wait-for-flux job
