### ISSUE TITLE
feat: implement hybrid configuration approach for CDKTF migration

### ISSUE THREAD

**Issue by willgriffin** [willgriffin/startup-gitops-template#80]
## Summary

Following analysis of the current CDKTF migration, we need to implement a hybrid configuration approach that balances automation with GitOps principles. The current CLI/CDKTF setup doesn't handle all the configuration steps that the initial-setup script performed, particularly around Flux manifest configuration.

### What's Missing in CLI/CDKTF:
1. **Flux Manifest Templating** - Initial-setup script does find/replace on all YAML files, but CLI/CDKTF leaves manifests with hardcoded example values
2. **Additional Infrastructure Setup** - Spaces bucket, access keys, AWS IAM user for SES, GitHub secrets
3. **GitHub Project & Workflow Setup** - Labels, project board, automation

### Key Finding:
The Flux manifests in `/flux/` are static YAML files with placeholder values (`example.com`, `my-cluster`, etc.) with no dynamic templating currently implemented.

### Static Configuration (One-Time Setup)
- Domain names and application URLs
- Namespace structure
- Service names  
- Network policies
- Cluster name references

### Dynamic Configuration (Ongoing via ConfigMap)
- Resource profiles (CPU/memory sizing)
- Storage classes and sizes
- Node selectors
- Replica counts
- Infrastructure-dependent settings

### 1. Enhanced CDKTF Setup
```typescript
class PostDeploymentSetup {
  // One-time manifest configuration
  async configureStaticValues(config: Config) {
    // Replace domains, cluster names, etc.
    await replaceInFiles({
      'example.com': config.domain,
      'my-cluster': config.clusterName,
      // etc...
    });
  }
  
  // Dynamic infrastructure ConfigMap
  async createInfrastructureConfig(config: Config) {
    // Generate ConfigMap with resource profiles
    // Deploy to flux-system namespace
  }
}
```

### 2. Infrastructure ConfigMap Structure
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: infrastructure-config
  namespace: flux-system
data:
  values.yaml:  < /dev/null | 
    resourceProfiles:
      small: { cpu: "500m", memory: "1Gi" }
      medium: { cpu: "1", memory: "2Gi" }
      large: { cpu: "2", memory: "4Gi" }
    storageClasses:
      fast: { size: "10Gi", type: "do-block-storage" }
      bulk: { size: "100Gi", type: "do-spaces" }
    nodeSelector:
      size: ${nodeSize}
```

### 3. Flux Variable Substitution
Update application HelmReleases to use Flux's native variable substitution:
```yaml
spec:
  valuesFrom:
    - kind: ConfigMap
      name: infrastructure-config
  values:
    resources: ${resourceProfiles.medium}
```

### 4. Simplified User Flow
```bash
# Create config
cp config.yaml.example config.yaml
# Edit config.yaml

# Deploy everything (one command)
gitops-cli deploy

# Done - infrastructure updates automatically,
# manifests can be customized directly
```

## Benefits

1. **Preserves GitOps** - Git remains source of truth for application configuration
2. **Simplifies Setup** - One config file, one command
3. **Flexible Evolution** - Users can override any dynamic values by editing manifests
4. **Infrastructure Sync** - Resource sizing stays consistent with cluster configuration
5. **No External Dependencies** - Uses Flux's built-in features

## Tasks

- [ ] Add one-time manifest configuration to CDKTF deployment
- [ ] Implement infrastructure ConfigMap generation
- [ ] Update Flux manifests to use variable substitution where appropriate
- [ ] Remove initial-setup.sh script
- [ ] Update documentation for new setup flow
- [ ] Test migration path from existing deployments

## Related Context

This addresses the gap between the initial-setup script's comprehensive configuration approach and the current CDKTF implementation, while maintaining the GitOps philosophy where Git is the authoritative source for desired state.

/cc @willgriffin
