### ISSUE TITLE
Add job timeouts to prevent hanging workflows

### ISSUE THREAD

**Issue by willgriffin** [willgriffin/startup-gitops-template#9]
## Description
The workflow jobs lack explicit timeout configurations, which could lead to stuck workflows consuming GitHub Actions minutes indefinitely.

## Problem
- Jobs can hang indefinitely
- Wastes GitHub Actions minutes
- Blocks subsequent deployments
- No automatic cleanup of stuck jobs

## Proposed Solution
1. Add timeout-minutes to all jobs
2. Set reasonable defaults based on job type
3. Make timeouts configurable
4. Add timeout notifications

## Implementation Example
```yaml
jobs:
  validate-config:
    timeout-minutes: 5
    # ...
  
  setup-secrets:
    timeout-minutes: 10
    # ...
  
  deploy-infrastructure:
    timeout-minutes: 30
    # ...
  
  generate-encrypted-secrets:
    timeout-minutes: 10
    # ...
  
  wait-for-flux:
    timeout-minutes: 20
    # Already has timeout on wait command, but job should too
  
  destroy-infrastructure:
    timeout-minutes: 20
    # ...
```

## Benefits
- Prevents runaway costs
- Faster failure detection
- Better resource management
- Clearer expectations

## References
- No job-level timeouts defined
- Only wait-for-flux has step timeout (line 322)
- GitHub default is 360 minutes
